config/routes.rb
Rails.application.routes.draw do
  resources :professors do
  	resources :reviews
	end
  resources :records
  get 'home/index'
  root 'classrooms#index'
  resources :classrooms do
		resources :rates
	end

  # root 'class#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :professor, :through => :record

	has_many :rates, dependent: :delete_all
	has_many :professor, :through => :rates

	validates :title, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :rates, dependent: :delete_all
	has_many :reviews, dependent: :delete_all
	has_many :classroom, :through => :record
	validates :name, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor_class.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :professor
  belongs_to :classroom
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :professor
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	def new
	end

	def index
		@classrooms = Classroom.all
	end

	def new
		@classroom = Classroom.new
		@professors = Professor.all
	end

	def edit
		@classroom = Classroom.find(params[:id])
		@records = @classroom.record
		@professors = Professor.all
	end

	def create
		@classroom = Classroom.new(classroom_params)
		@record = @classroom.record.new(record_params)

				
		if @classroom.save and @record.save
		   redirect_to classrooms_path
		 else
	 		@professors = Professor.all
			render 'new'
	    end
	end

	def destroy
		@classroom = Classroom.find(params[:id])
	  	@classroom.destroy
		respond_to do |format|
			format.html { redirect_to classrooms_url, :flash => { :error => 'Class was successfully destroyed.' }  }
		    format.json { head :no_content }
		end
	end


	def update
		@classroom = Classroom.find(params[:id])
		@professors = Professor.all


		if @classroom.update(classroom_params)
			params_set = params[:classroom][:professor_id].map(&:to_i)
			Record.destroy(@classroom.record.ids)
			params_set.each do |a|
				@classroom.record.create(professor_id: a)
			end
	   		redirect_to @classroom
		else
		   render 'edit'
		end
	end

	def show
		@classroom = Classroom.find(params[:id])
	end

	# DELETE /professors/1
	# DELETE /professors/1.json
	def destroy_professor
	  @professor.destroy
	  respond_to do |format|
	    format.html { redirect_to professors_url,  :flash => { :error => 'Professor was successfully destroyed.' } }
	    format.json { head :no_content }
	  end
	end


	private
	  def classroom_params
	    params.require(:classroom).permit(:title, :text, :professor)
	  end	 

   	def record_params
	    params.require(:classroom).permit(:professor_ids)
	  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url,  :flash => { :error => 'Professor was successfully deleted.' } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

	def create
		@classroom = Classroom.find(params[:classroom_id])
	  @rates = @classroom.rates.create(professor_id: params[:professor_id], review: params[:rate][:review], rating: params[:rate][:rating] )

	  respond_to do |format|
		  if @classroom.save
		  	  format.html { redirect_to classroom_path(@classroom), notice: 'Review was successfully created.' }
		  	  format.json { render :show, status: :created, location: @professor }
	  	else
	  	  format.html { redirect_to classroom_path(@classroom), :flash => { :error => @rates.errors.full_messages.to_sentence } }
	  	  format.json { render json: @classroom.errors, status: :unprocessable_entity }
	  	end
  	end
	end

	private
    def reviews_param
      params.require(:rate).permit(:review)
    end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	def destroy
		@last_url = URI(request.referer || '').path
		@record = Record.find(params[:id])
		@record.destroy

		respond_to do |format|
		  format.html { redirect_to @last_url, :flash => { :error => 'Professor was successfully deleted.' } }
		  format.json { head :no_content }
		end
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@professor = Professor.find(params[:professor_id])
		@reviews = @professor.reviews.create(reviews_param)
		redirect_to professor_path(@professor)
	end

	private
	    def reviews_param
	      params.require(:review).permit(:review)
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_class?(test_path)
	   return 'active' if request.path == test_path
	   ''
	 end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/classrooms/_form.html.erb
<div class="col-md-5">
  <%= form_with model: @classroom, local: true do |form| %>
   
    <% if @classroom.errors.any? %>
      <div class="alert alert-danger">
        <p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= pluralize(@classroom.errors.count, "error") %> prohibited
          this classroom from being saved:
        </p>
        <ul>
          <% @classroom.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <%= form.label :title %><br>
    <%= form.text_field :title, :class=>'form-control'%>
    <br>     
    <%= form.label :professor %>
    <br>

    <%= form.collection_select :professor_id, @professors, :id, :name, {prompt: false}, { class: "form-control", multiple: "multiple"} %>
    
    <br>
    <br>
    <%= form.label :text %><br>
    <%= form.text_area :text, :class=>'form-control', rows: "10" %>
   <br>
    <div class="inline-group"><%= form.submit 'Submit', :class=>'btn btn-success' %>
        <%= link_to 'Back', classrooms_path, :class=>'btn btn-success' %></div>
   
  <% end %>
</div>

<script>
  $(function(){
    $('#classroom_professor_id').select2();
    <% if !@classroom.record.ids.empty? %>
    $('#classroom_professor_id').val(<%= @records.pluck(:professor_id) %>).change();
    <% end %>
  });
</script>

app/views/classrooms/edit.html.erb
<% content_for :title, "Edit class: " << @classroom.title %>
<h4>Edit Classroom</h4>

<%= render 'form' %>
 

app/views/classrooms/index.html.erb
<% content_for :title, 'Class List' %>

<% if notice %>
	<div id="notice" class="alert alert-success">
		<%= notice %>		
	</div>
<% end %>

<% if flash[:error] %>
<div class="alert alert-danger">
    <p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> </span> <%= flash[:error] %> </p>
</div>
<% end %>

<h4>Class List</h4>
<%= link_to 'Create New Class',  new_classroom_path, :class=>'btn btn-success pull-right'%>
<div class="clearfix"></div> <br>
<table class='table'>
	<tr>
		<th>Title</th>
		<th>Details</th>
		<th>Actions</th>
	</tr>
	<% @classrooms.each do |classroom| %>
	    <tr>
	      <td><%= link_to classroom.title, classroom_path(classroom)%></td>
	      <td><%= classroom.text %></td>
	      <td><%= link_to '', classroom_path(classroom), :class=>'glyphicon glyphicon-search' %>
	      <%= link_to '', edit_classroom_path(classroom), :class=>'glyphicon glyphicon-pencil' %>
	      <%= link_to '', classroom, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'glyphicon glyphicon-remove'%></td>
	    </tr>
	<% end %>
</table>

app/views/classrooms/new.html.erb
<% content_for :title, "Create Class"%>
<h4>Create Class</h4>

<%= render 'form' %>
 

app/views/classrooms/show.html.erb
<% content_for :title, @classroom.title %>

<% if notice %>
<div id="notice" class="alert alert-success">
    <%= notice %>
</div>
<% end %>
<% if flash[:error] %>
<div class="alert alert-danger">
    <p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> </span> <%= flash[:error] %> </p>
</div>
<% end %>
<h1><%= @classroom.title %></h1>
<p><%= @classroom.text %></p>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<% if @classroom.record.count > 0 %>
<% @classroom.record.each do |record| %>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#<%= record.id %>" aria-expanded="true" aria-controls="collapseOne">
            <h4 class="panel-title">
            <%= record.professor.name %>
            <p class="pull-right"><%= link_to '', record, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'glyphicon glyphicon-remove'%></p>
            </h4>
            <span class="clearfix"></span>
        </a>
        <%= 
            @avgRate =  @classroom.rates.where(professor_id: record.professor.id ).average(:rating)
            select_tag "", options_for_select((1..5).map { |i| ["#{i}", i] }, @avgRate.to_i), class: 'form-control readonly-star'  %>

    </div>
    <div id="<%= record.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <% @classroom.rates.where(professor_id: record.professor.id ).each do |rates| %>
            <p>
                <span class="glyphicon glyphicon-user"></span>
                <strong>Anonymous</strong>
                <%= rates.created_at.strftime("%B %e %Y") %>
            </p>
            <%= select_tag "", options_for_select((1..5).map { |i| ["#{i}", i] }, rates.rating ), class: 'form-control readonly-star'  %>
            <p><%= rates.review %></p>
            <br>
            <% end %>
            <h3>Add a review:</h3>
            <%= form_with(model: [ @classroom, @classroom.rates.build ], local: true) do |form| %>
            <%= hidden_field_tag(:professor_id, record.professor.id ) %>

            <%= form.select(:rating, options_for_select(1..5, 1) ,  {:prompt=>false}, {required: 'true', autofocus: 'true', class: 'rate_rating'})  %>
     
            <p>
                <%= form.text_area :review, :class=>'form-control' %>
            </p>
            <p>
                <%= form.submit 'Submit', :class=>'btn btn-success' %>
            </p>
            <% end %>
        </div>
    </div>
</div>
<% end %>
</div>
<% else %>
<h4>Notice:</h4>
<p>There is no assign professor to this class yet.</p>
<% end %>
<script type="text/javascript">
$(function() {
    $('.rate_rating').barrating({
        initialRating: 1,
        theme: 'bootstrap-stars'
    });
    $('.readonly-star').barrating({
        initialRating: 0,
        theme: 'bootstrap-stars',
        readonly: 'false',
    });
});
</script>