config/routes.rb
Rails.application.routes.draw do
  resources :professors do
  	resources :reviews
	end
  resources :records
  get 'home/index'
  root 'classrooms#index'
  resources :classrooms do
		resources :rates
	end

  # root 'class#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :professor, :through => :record

	has_many :rates, dependent: :delete_all
	has_many :professor, :through => :rates

	validates :title, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :rates, dependent: :delete_all
	has_many :reviews, dependent: :delete_all
	has_many :classroom, :through => :record
	validates :name, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor_class.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :professor
  belongs_to :classroom
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :professor
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
	def new
	end

	def index
		@classrooms = Classroom.all
	end

	def new
		@classroom = Classroom.new
		@professors = Professor.all
	end

	def edit
		@classroom = Classroom.find(params[:id])
		@records = @classroom.record
		@professors = Professor.all
	end

	def create
		@classroom = Classroom.new(classroom_params)
		@record = @classroom.record.new(record_params)

				
		if @classroom.save and @record.save
		   redirect_to classrooms_path
		 else
	 		@professors = Professor.all
			render 'new'
	    end
	end

	def destroy
		@classroom = Classroom.find(params[:id])
	  	@classroom.destroy
		respond_to do |format|
			format.html { redirect_to classrooms_url, :flash => { :error => 'Class was successfully destroyed.' }  }
		    format.json { head :no_content }
		end
	end


	def update
		@classroom = Classroom.find(params[:id])
		@professors = Professor.all


		if @classroom.update(classroom_params)
			params_set = params[:classroom][:professor_id].map(&:to_i)
			Record.destroy(@classroom.record.ids)
			params_set.each do |a|
				@classroom.record.create(professor_id: a)
			end
	   		redirect_to @classroom
		else
		   render 'edit'
		end
	end

	def show
		@classroom = Classroom.find(params[:id])
	end

	# DELETE /professors/1
	# DELETE /professors/1.json
	def destroy_professor
	  @professor.destroy
	  respond_to do |format|
	    format.html { redirect_to professors_url,  :flash => { :error => 'Professor was successfully destroyed.' } }
	    format.json { head :no_content }
	  end
	end


	private
	  def classroom_params
	    params.require(:classroom).permit(:title, :text, :professor)
	  end	 

   	def record_params
	    params.require(:classroom).permit(:professor_ids)
	  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url,  :flash => { :error => 'Professor was successfully deleted.' } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

	def create
		@classroom = Classroom.find(params[:classroom_id])
	  @rates = @classroom.rates.create(professor_id: params[:professor_id], review: params[:rate][:review], rating: params[:rate][:rating] )

	  respond_to do |format|
		  if @classroom.save
		  	  format.html { redirect_to classroom_path(@classroom), notice: 'Review was successfully created.' }
		  	  format.json { render :show, status: :created, location: @professor }
	  	else
	  	  format.html { redirect_to classroom_path(@classroom), :flash => { :error => @rates.errors.full_messages.to_sentence } }
	  	  format.json { render json: @classroom.errors, status: :unprocessable_entity }
	  	end
  	end
	end

	private
    def reviews_param
      params.require(:rate).permit(:review)
    end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	def destroy
		@last_url = URI(request.referer || '').path
		@record = Record.find(params[:id])
		@record.destroy

		respond_to do |format|
		  format.html { redirect_to @last_url, :flash => { :error => 'Professor was successfully deleted.' } }
		  format.json { head :no_content }
		end
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@professor = Professor.find(params[:professor_id])
		@reviews = @professor.reviews.create(reviews_param)
		redirect_to professor_path(@professor)
	end

	private
	    def reviews_param
	      params.require(:review).permit(:review)
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_class?(test_path)
	   return 'active' if request.path == test_path
	   ''
	 end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/professors/_form.html.erb
<div class="col-md-5">
  <%= form_with(model: professor, local: true) do |form| %>
    <% if professor.errors.any? %>
    <div class="alert alert-danger" role="alert">
        
        <p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</p>
  
        <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form.label :name %>
    <%= form.text_field :name , :class=>'form-control' %>
  
    <br>
    <div class="inline-group">
      <%= form.submit 'Submit', :class=>'btn btn-success'  %>
      <%= link_to 'Back', professors_path, :class=>'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/professors/edit.html.erb
<% content_for :title, "Edit class: " << @professor.name %>

<h4>Edit Professor</h4>

<%= render 'form', professor: @professor %>

app/views/professors/index.html.erb
<% content_for :title, 'Professor List' %>

<% if notice %>
  <div id="notice" class="alert alert-success">
    <%= notice %>   
  </div>
<% end %>

<% if flash[:error] %>
<div class="alert alert-danger">
    <p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"> </span> <%= flash[:error] %> </p>
</div>
<% end %>

<h4>Professors</h4>

<%= link_to 'Create New Professor', new_professor_path, :class=>'btn btn-success pull-right'%>
<div class="clearfix"></div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= link_to professor.name, professor %> </td>
        <td>
          <%= link_to '', professor, :class=>'glyphicon glyphicon-search' %>
          <%= link_to '', edit_professor_path(professor), :class=>'glyphicon glyphicon-pencil' %>
          <%= link_to '', professor, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/professors/new.html.erb
<% content_for :title, "New Professor"%>
<h4>New Professor</h4>

<%= render 'form', professor: @professor %>

app/views/professors/show.html.erb
<% content_for :title, @professor.name %>
<% if notice %>
<div id="notice" class="alert alert-success">
	<%= notice %>
</div>
<% end %>

<p>
	<h4>
		<%= @professor.name %>
		<%=
					@overallAvg =  @professor.rates.average(:rating)
					select_tag "", options_for_select((1..5).map { |i| ["#{i}", i] }, @overallAvg.to_i), class: 'form-control readonly-star'  
		%>

	</h4>
</p>
<h2>Class List:</h2>
<table class="table">
	<tr>
		<th>Class Name</th>
		<th>Action</th>
	</tr>
	<% @professor.record.each do |record| %>
	<tr>
		<td><%= record.classroom.title %></td>
		<td>            
			<%= 
			@avgRate =  @professor.rates.where(classroom_id: record.classroom.id ).average(:rating)
			select_tag "", options_for_select((1..5).map { |i| ["#{i}", i] }, @avgRate.to_i), class: 'form-control readonly-star'  %>
		</td>
		<td><%= link_to '', record, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'glyphicon glyphicon-remove'%></td>
	</tr>
	<% end %>
</table>
<h3>Add a review:</h3>
<%= form_with(model: [ @professor, @professor.reviews.build ], local: true) do |form| %>
<p>
	<%= form.text_area :review, :class=>'form-control' %>
</p>
<p>
	<%= form.submit 'Submit', :class=>'btn btn-success' %>
</p>
<% end %>
<br>
<h2>Reviews</h2>
<% @professor.reviews.each do |review| %>
	<% if review.review %>
	<p>
	    <span class="glyphicon glyphicon-user"></span>
	    <strong>Anonymous</strong>
	    <%= review.created_at.strftime("%B %e %Y") %>
	</p>
	<p><%= review.review %></p>
	<br>
	<% end %>
<% end %>
<script type="text/javascript">
$(function() {
    $('.readonly-star').barrating({
        initialRating: 0,
        theme: 'bootstrap-stars',
        readonly: 'false',
    });
});
</script>