config/routes.rb
Rails.application.routes.draw do
  resources :professors do
  	resources :reviews
	end
  resources :records
  get 'home/index'
  root 'classrooms#index'
  resources :classrooms do
		resources :rates
	end

  # root 'class#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :professor, :through => :record

	has_many :rates, dependent: :delete_all
	has_many :professor, :through => :rates

	validates :title, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor.rb
class Professor < ApplicationRecord
	has_many :record, dependent: :delete_all
	has_many :rates, dependent: :delete_all
	has_many :reviews, dependent: :delete_all
	has_many :classroom, :through => :record
	validates :name, presence: true,
	                    length: { minimum: 5 }
end

app/models/professor_class.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :professor
  belongs_to :classroom
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :classroom
	belongs_to :professor

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :professor
  validates :review, presence: true,
                      length: { minimum: 5 }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

	def create
		@classroom = Classroom.find(params[:classroom_id])
	  @rates = @classroom.rates.create(professor_id: params[:professor_id], review: params[:rate][:review], rating: params[:rate][:rating] )

	  respond_to do |format|
		  if @classroom.save
		  	  format.html { redirect_to classroom_path(@classroom), notice: 'Review was successfully created.' }
		  	  format.json { render :show, status: :created, location: @professor }
	  	else
	  	  format.html { redirect_to classroom_path(@classroom), :flash => { :error => @rates.errors.full_messages.to_sentence } }
	  	  format.json { render json: @classroom.errors, status: :unprocessable_entity }
	  	end
  	end
	end

	private
    def reviews_param
      params.require(:rate).permit(:review)
    end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	def destroy
		@last_url = URI(request.referer || '').path
		@record = Record.find(params[:id])
		@record.destroy

		respond_to do |format|
		  format.html { redirect_to @last_url, :flash => { :error => 'Professor was successfully deleted.' } }
		  format.json { head :no_content }
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_class?(test_path)
	   return 'active' if request.path == test_path
	   ''
	 end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/classroom_helper.rb
module ClassroomHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
         <nav class="navbar navbar-default">
           <div class="container-fluid">
             <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="<%= root_path %>">Class</a>
             </div>
             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav navbar-right">
                 <li class="<%= current_class?(classrooms_path)  %>"><%= link_to "Class", classrooms_path, :class => current_class?(classrooms_path)  %></li>
                 <li class="<%= current_class?(professors_path)  %>"><%= link_to "Professors", professors_path %></li>
               </ul>
                 </li>
               </ul>
             </div>
           </div>
         </nav>          
         <%= yield %>        
      </div>
    </div>
  </body>
</html>